import type { JobGroupEnumType } from '@/types/signup.ts'
import type { RecruitmentTypeEnum, RecruitmentTypeKor } from '@/types/job.ts'

export const changeEducationKorToEnum = (education: string) => {
  switch (education) {
    case '학사':
      return 'BACHELOR'
    case '석사':
      return 'MASTER'
    case '고졸':
      return 'HIGH_SCHOOL'
    case '초대졸':
      return 'JUNIOR_COLLEGE'
    case '박사':
      return 'DOCTOR'
    case '무관':
      return 'IRRELEVANT'
  }
}

export function getJobCategory(category: string) {
  switch(category) {
    case "IT/개발":
      return "IT_개발";
    case "AI/데이터":
      return "AI_데이터";
    case "게임":
      return "게임";
    case "디자인":
      return "디자인";
    case "기획/전략":
      return "기획_전략_경영";
    case "마케팅/광고/홍보":
      return "마케팅_광고_홍보";
    case "상품기획/MD":
      return "상품기획_MD";
    case "영업":
      return "영업";
    case "무역/물류/유통":
      return "무역_물류_유통";
    case "운송/배송":
      return "운송_배송";
    case "법률/법무":
      return "법률_법무";
    case "HR/총무":
      return "인사_노무_HRD_총무";
    case "회계/세무/재무":
      return "회계_세무_재무";
    case "증권/운영":
      return "증권_운영";
    case "은행/카드/보험":
      return "은행_보험_카드_캐피탈";
    case "엔지니어링/R&D":
      return "엔지니어링_연구_RND";
    case "건설/건축":
      return "건설_건축";
    case "생산/기능직":
      return "생산_기능";
    case "의료/보건":
      return "의료_보건";
    case "공공/복지":
      return "공공_복지";
    case "교육":
      return "교육";
    case "미디어/엔터":
      return "미디어_엔터";
    case "고객상담/TM":
      return "고객상담_TM";
    case "서비스":
      return "서비스";
    case "식음료":
      return "식음료";
  }
}

export function getITJobCategory(category: string) {
  switch(category) {
    case "서버·백엔드":
      return "서버_백엔드";
    case "프론트엔드":
      return "프론트엔드";
    case "웹풀스택":
      return "웹풀스택";
    case "안드로이드":
      return "안드로이드";
    case "iOS":
      return "iOS";
    case "크로스 플랫폼":
      return "크로스_플랫폼";
    case "DBA":
      return "DBA";
    case "DevOps·SRE":
      return "DevOps_SRE";
    case "시스템·네트워크":
      return "시스템_네트워크";
    case "시스템소프트웨어":
      return "시스템소프트웨어";
    case "소프트웨어 엔지니어":
      return "소프트웨어_엔지니어";
    case "정보보호·보안":
      return "정보보호_보안";
    case "임베디드 소프트웨어":
      return "임베디드소프트웨어";
    case "로봇SW":
      return "로봇SW";
    case "QA·테스트":
      return "QA_테스트";
    case "사물인터넷(IoT)":
      return "사물인터넷_IoT";
    case "응용 프로그램":
      return "응용_프로그램";
    case "블록체인":
      return "블록체인";
    case "개발PM":
      return "개발PM";
    case "웹 퍼블리싱":
      return "웹퍼블리싱";
    case "VR·AR·3D":
      return "VR_AR_3D";
    case "ERP·SAP":
      return "ERP_SAP";
    case "그래픽스":
      return "그래픽스";
    case "하드웨어엔지니어":
      return "하드웨어엔지니어";
    case "기타IT·개발":
      return "기타IT_개발";
    case "기술지원":
      return "기술지원";
  }
}

export const changeCategoryEnumToKor = (selectedCategory: JobGroupEnumType | undefined | null) => {
  switch (selectedCategory) {
    case 'IT_개발':
      return 'IT 개발'
    case 'AI_데이터':
      return 'AI 데이터'
    case '엔지니어링_연구_RND':
      return '엔지니어링 R&D'
    case '건설_건축':
      return '건설 건축'
    case '생산_기능':
      return '생산 기능직'
    case '법률_법무':
      return '법률 법무'
    case '증권_운영':
      return '증권 운영'
    case '은행_보험_카드_캐피탈':
      return '은행 카드 보험'
    case '의료_보건':
      return '의료 보건'
    case '공공_복지':
      return '공공 복지'
    case '교육':
      return '교육'
    case '식음료':
      return '식음료'
    case '마케팅_광고_홍보':
      return '마케팅 광고'
    case '디자인':
      return '디자인'
    case '게임':
      return '게임'
    case '미디어_엔터':
      return '미디어 엔터'
    case '고객상담_TM':
      return '고객상담 TM'
    case '서비스':
      return '서비스'
    case '기획_전략_경영':
      return '기획 전략'
    case '상품기획_MD':
      return '상품기획 MD'
    case '영업':
      return '영업'
    case '무역_물류_유통':
      return '무역 물류'
    case '운송_배송':
      return '운송 배송'
    case '회계_세무_재무':
      return '회계 재무 세무'
    case '인사_노무_HRD_총무':
      return 'HR 총무'
  }
}


export function getDetailJobCategory(category: string) {
  switch(category) {
    // IT·개발
    case "서버·백엔드":
      return "서버_백엔드";
    case "프론트엔드":
      return "프론트엔드";
    case "웹풀스택":
      return "웹풀스택";
    case "안드로이드":
      return "안드로이드";
    case "iOS":
      return "iOS";
    case "크로스 플랫폼":
      return "크로스_플랫폼";
    case "DBA":
      return "DBA";
    case "DevOps·SRE":
      return "DevOps_SRE";
    case "시스템·네트워크":
      return "시스템_네트워크";
    case "시스템소프트웨어":
      return "시스템소프트웨어";
    case "소프트웨어 엔지니어":
      return "소프트웨어_엔지니어";
    case "정보보호·보안":
      return "정보보호_보안";
    case "임베디드 소프트웨어":
      return "임베디드소프트웨어";
    case "로봇SW":
      return "로봇SW";
    case "QA·테스트":
      return "QA_테스트";
    case "사물인터넷(IoT)":
      return "사물인터넷_IoT";
    case "응용 프로그램":
      return "응용_프로그램";
    case "블록체인":
      return "블록체인";
    case "개발PM":
      return "개발PM";
    case "웹 퍼블리싱":
      return "웹퍼블리싱";
    case "VR·AR·3D":
      return "VR_AR_3D";
    case "ERP·SAP":
      return "ERP_SAP";
    case "그래픽스":
      return "그래픽스";
    case "하드웨어엔지니어":
      return "하드웨어엔지니어";
    case "기타IT·개발":
      return "기타IT_개발";
    case "기술지원":
      return "기술지원";

    // AI·데이터
    case "데이터 분석가":
      return "데이터_분석가";
    case "데이터 사이언티스트":
      return "데이터_사이언티스트";
    case "데이터 엔지니어":
      return "데이터_엔지니어";
    case "머신러닝 엔지니어":
      return "머신러닝_엔지니어";
    case "멀티모달엔지니어":
      return "멀티모달엔지니어";
    case "생성형AI":
      return "생성형AI";
    case "영상·음성AI":
      return "영상_음성AI";
    case "자율주행":
      return "자율주행";
    case "컴퓨터 비전":
      return "컴퓨터비전";
    case "AI 비즈니스":
      return "AI_비즈니스";
    case "AI 서비스 기획":
      return "AI_서비스_기획";
    case "AI리서치":
      return "AI리서치";
    case "NLP":
      return "NLP";
    case "LLM":
      return "LLM";
    case "MLOps":
      return "MLOps";
    case "RAG":
      return "RAG";
    case "기타AI·데이터":
      return "기타AI_데이터";

    // 게임
    case "게임기획·PM":
      return "게임기획_PM";
    case "게임운영":
      return "게임운영";
    case "게임QA":
      return "게임QA";
    case "게임개발(클라이언트)":
      return "게임개발_클라이언트";
    case "게임개발(서버)":
      return "게임개발_서버";
    case "게임개발(모바일)":
      return "게임개발_모바일";
    case "테크니컬아티스트":
      return "테크니컬아티스트";
    case "게임아트":
      return "게임아트";
    case "게임3D모델링":
      return "게임3D모델링";
    case "게임애니메이션":
      return "게임애니메이션";
    case "게임이펙트·FX":
      return "게임이펙트_FX";
    case "게임인터페이스":
      return "게임인터페이스";
    case "게임연출·영상":
      return "게임연출_영상";
    case "게임사운드":
      return "게임사운드";
    case "기타게임":
      return "기타게임";

    // 디자인
    case "UIUX·프로덕트":
      return "UIUX_프로덕트";
    case "웹디자인":
      return "웹디자인";
    case "디자인리서치":
      return "디자인리서치";
    case "그래픽·시각":
      return "그래픽_시각";
    case "일러스트레이터":
      return "일러스트레이터";
    case "브랜딩·BIBX":
      return "브랜딩_BIBX";
    case "공간·실내·VMD":
      return "공간_실내_VMD";
    case "산업(제품)":
      return "산업_제품";
    case "패키지":
      return "패키지";
    case "광고·콘텐츠":
      return "광고_콘텐츠";
    case "영상·모션":
      return "영상_모션";
    case "3D·VFX":
      return "VFX_3D";
    case "출판·편집":
      return "출판_편집";
    case "건축·공공·조경디자인":
      return "건축_공공_조경디자인";
    case "패션·텍스타일":
      return "패션_텍스타일";
    case "기타디자인":
      return "기타디자인";

    // 기획·전략
    case "PM·PO":
      return "PM_PO";
    case "서비스·상품기획":
      return "서비스_상품기획";
    case "사업·전략기획":
      return "사업_전략기획";
    case "컨설팅":
      return "컨설팅";
    case "기술기획":
      return "기술기획";
    case "사업개발·분석":
      return "사업개발_분석";
    case "프로젝트 매니저":
      return "프로젝트_매니저";
    case "운영관리(OM)":
      return "운영관리_OM";
    case "경영지원":
      return "경영지원";
    case "기타기획·전략·경영":
      return "기타기획_전략_경영";

    // 마케팅
    case "마케팅기획·전략":
      return "마케팅기획_전략";
    case "퍼포먼스 마케팅":
      return "퍼포먼스마케팅";
    case "콘텐츠마케팅":
      return "콘텐츠마케팅";
    case "SNS마케팅":
      return "SNS마케팅";
    case "브랜드 마케팅":
      return "브랜드마케팅";
    case "CRM마케팅":
      return "CRM마케팅";
    case "글로벌 마케팅":
      return "글로벌마케팅";
    case "광고기획(AE)":
      return "광고기획_AE";
    case "홍보·PR":
      return "홍보_PR";
    case "전시·행사 마케팅":
      return "전시_행사마케팅";
    case "기타마케팅":
      return "기타마케팅";

    // 상품기획/MD
    case "상품기획":
      return "상품기획";
    case "온라인MD":
      return "온라인MD";
    case "식품MD":
      return "식품MD";
    case "패션MD":
      return "패션MD";
    case "뷰티MD":
      return "뷰티MD";
    case "영업MD":
      return "영업MD";
    case "리테일MD":
      return "리테일MD";
    case "기타상품기획·MD":
      return "기타상품기획_MD";

    // 영업
    case "B2C영업":
      return "B2C영업";
    case "B2B영업":
      return "B2B영업";
    case "영업관리·지원":
      return "영업관리_지원";
    case "일반영업":
      return "일반영업";
    case "기술·IT영업":
      return "기술_IT영업";
    case "금융·보험영업":
      return "금융_보험영업";
    case "해외영업":
      return "해외영업";
    case "제약·의료영업":
      return "제약_의료영업";
    case "기타 영업":
      return "기타영업";
    case "해외·상사영업":
      return "해외_상사영업";
    case "구매":
      return "구매";

    // 무역·물류
    case "수출입관리·사무":
      return "수출입관리_사무";
    case "관세사":
      return "관세사";
    case "무역금융":
      return "무역금융";
    case "포워딩":
      return "포워딩";
    case "구매·조달":
      return "구매_조달";
    case "물류·SCM":
      return "물류_SCM";
    case "입출고·포장":
      return "입출고_포장";
    case "자재·재고관리":
      return "자재_재고관리";
    case "운송":
      return "운송";
    case "유통관리":
      return "유통관리";
    case "설비·시설관리":
      return "설비_시설관리";
    case "기타무역·물류·유통":
      return "기타무역_물류_유통";
    case "배송·배달":
      return "배송_배달";
    case "승객운송":
      return "승객운송";
    case "물류운송":
      return "물류운송";
    case "전문운전":
      return "전문운전";
    case "배차관리":
      return "배차관리";
    case "기타운전·운송":
      return "기타운전_운송";

    // 법률
    case "변호사":
      return "변호사";
    case "변리사":
      return "변리사";
    case "법무":
      return "법무";
    case "컴플라이언스":
      return "컴플라이언스";
    case "내부감사":
      return "내부감사";
    case "ESG·윤리":
      return "ESG_윤리";
    case "특허·IP":
      return "특허_IP";
    case "기타법률":
      return "기타법률";

    // HR/총무
    case "인사기획":
      return "인사기획";
    case "평가·보상":
      return "평가_보상";
    case "HRD·조직문화":
      return "HRD_조직문화";
    case "리크루터·헤드헌터":
      return "리크루터_헤드헌터";
    case "노무관리":
      return "노무관리";
    case "총무·비서":
      return "총무_비서";
    case "기타 HR·총무":
      return "기타HR_총무";

    // 회계/세무/재무
    case "회계":
      return "회계";
    case "재무":
      return "재무";
    case "세무":
      return "세무";
    case "IR_공시":
      return "IR_공시";
    case "경리_회계보조":
      return "경리_회계보조";
    case "기타회계_재무_세무":
      return "기타회계_재무_세무";

    // 포털/채용 플랫폼
    case "직행수집":
      return "직행수집";
    case "원티드":
      return "원티드";
    case "그룹바이":
      return "그룹바이";
    case "랠릿":
      return "랠릿";
    case "로켓펀치":
      return "로켓펀치";
    case "고용24":
      return "고용24";
    case "아이원잡":
      return "아이원잡";
    case "중소벤처기업진흥공단":
      return "중소벤처기업진흥공단";
    case "IBRIC":
      return "IBRIC";
    case "클린아이":
      return "클린아이";
    case "아트모아":
      return "아트모아";
    case "복지넷":
      return "복지넷";
    case "한국상담학회":
      return "한국상담학회";
    case "잡스포이즈":
      return "잡스포이즈";
    case "금융투자협회":
      return "금융투자협회";
    case "한국금융벤처캐피탈협회":
      return "한국금융벤처캐피탈협회";
    case "한국공인회계사회":
      return "한국공인회계사회";
    case "여신금융협회":
      return "여신금융협회";
    case "한국관세사회":
      return "한국관세사회";
    case "한국보험계리사회":
      return "한국보험계리사회";
    case "인재채움뱅크":
      return "인재채움뱅크";
    case "잡알리오":
      return "잡알리오";
    case "나라일터":
      return "나라일터";
    case "농촌일자리플러스":
      return "농촌일자리플러스";
    case "도농인력중개플랫폼":
      return "도농인력중개플랫폼";
    case "국민참여일자리":
      return "국민참여일자리";
    case "외교부인사센터":
      return "외교부인사센터";
    case "대한상공회의소":
      return "대한상공회의소";
    case "병역일터":
      return "병역일터";

    // 금융/증권/운용
    case "운용·트레이딩":
      return "운용_트레이딩";
    case "리스크·준법·심사":
      return "리스크_준법_심사";
    case "VC·PE":
      return "VC_PE";
    case "증권IB":
      return "증권IB";
    case "부동산·인프라금융":
      return "부동산_인프라금융";
    case "PB·WM":
      return "PB_WM";
    case "경영지원·관리":
      return "경영지원_관리";
    case "금융상품개발·영업":
      return "금융상품개발_영업";
    case "기타증권·운용":
      return "기타증권_운용";
    case "은행":
      return "은행";
    case "카드사":
      return "카드사";
    case "캐피탈":
      return "캐피탈";
    case "보험설계":
      return "보험설계";
    case "계리":
      return "계리";
    case "손해사정":
      return "손해사정";
    case "언더라이팅·심사":
      return "언더라이팅_심사";
    case "청구·보상":
      return "청구_보상";
    case "보험상품개발":
      return "보험상품개발";
    case "기타은행·보험":
      return "기타은행_보험";

    // 엔지니어링/R&D
    case "반도체·디스플레이":
      return "반도체_디스플레이";
    case "전기·전자·제어":
      return "전기_전자_제어";
    case "통신기술·네트워크구축":
      return "통신기술_네트워크구축";
    case "기계":
      return "기계";
    case "기계설계·CAD":
      return "기계설계_CAD";
    case "자동차":
      return "자동차";
    case "조선·항공·우주":
      return "조선_항공_우주";
    case "금속·철강":
      return "금속_철강";
    case "화학":
      return "화학";
    case "화장품":
      return "화장품";
    case "바이오·제약":
      return "바이오_제약";
    case "식품":
      return "식품";
    case "에너지":
      return "에너지";
    case "환경":
      return "환경";
    case "기타엔지니어링·R&D":
      return "기타엔지니어링_RnD";
    case "자동화":
      return "자동화";

    // 건설/건축
    case "건축설계·시공":
      return "건축설계_시공";
    case "토목·측량·조경·환경":
      return "토목_측량_조경_환경";
    case "기계·전기·소방·설비":
      return "기계_전기_소방_설비";
    case "설계·감리·시공·공무":
      return "설계_감리_시공_공무";
    case "안전·품질·재료":
      return "안전_품질_재료";
    case "사무·관리·전산":
      return "사무_관리_전산";
    case "건설특수·일용직":
      return "건설특수_일용직";
    case "기타건설·건축":
      return "기타건설_건축";

    // 생산/기능직
    case "생산":
      return "생산";
    case "공무":
      return "공무";
    case "설비":
      return "설비";
    case "환경안전":
      return "환경안전";
    case "물류":
      return "물류";
    case "품질":
      return "품질";
    case "건설·공사·프로젝트":
      return "건설_공사_프로젝트";
    case "설계·CAD·CAM":
      return "설계_CAD_CAM";
    case "시설관리":
      return "시설관리";
    case "기타생산·기능직":
      return "기타생산_기능직";

    // 의료/보건
    case "의사":
      return "의사";
    case "한의사":
      return "한의사";
    case "수의사":
      return "수의사";
    case "약사·약무보조":
      return "약사_약무보조";
    case "간호사":
      return "간호사";
    case "간호조무사":
      return "간호조무사";
    case "치위생사":
      return "치위생사";
    case "응급구조사":
      return "응급구조사";
    case "물리치료·작업치료":
      return "물리치료_작업치료";
    case "영상의학·임상병리·검사":
      return "영상의학_임상병리_검사";
    case "영양사·임상영양사":
      return "영양사_임상영양사";
    case "의료미용·에스테틱":
      return "의료미용_에스테틱";
    case "병원행정·접수·수납":
      return "병원행정_접수_수납";
    case "요양보호사":
      return "요양보호사";
    case "조리원":
      return "조리원";
    case "안경·검안사":
      return "안경_검안사";
    case "기타의료·보건":
      return "기타의료_보건";

    // 공공/복지
    case "행정·사무·운영":
      return "행정_사무_운영";
    case "기술·전산·시설":
      return "기술_전산_시설";
    case "복지·사회서비스":
      return "복지_사회서비스";
    case "교육·연구":
      return "교육_연구";
    case "공공안전":
      return "공공안전";
    case "상담·심리":
      return "상담_심리";
    case "종교":
      return "종교";
    case "아동·청소년복지":
      return "아동_청소년복지";
    case "노인·여성복지":
      return "노인_여성복지";
    case "자원봉사":
      return "자원봉사";
    case "기타공공·복지":
      return "기타공공_복지";

    // 교육
    case "유치원·보육교사":
      return "유치원_보육교사";
    case "기간제·사립교사":
      return "기간제_사립교사";
    case "방과후·사립교사":
      return "방과후_사립교사";
    case "대학교수·강사":
      return "대학교수_강사";
    case "교직원·조교":
      return "교직원_조교";
    case "입시학원강사":
      return "입시학원강사";
    case "국어·외국어강사":
      return "국어_외국어강사";
    case "기술·전문강사":
      return "기술_전문강사";
    case "학습지·방문교사":
      return "학습지_방문교사";
    case "학원상담·운영":
      return "학원상담_운영";
    case "교재개발·교수설계":
      return "교재개발_교수설계";
    case "기타교육":
      return "기타교육";
    case "교육관리":
      return "교육관리";

    // 미디어/엔터
    case "PD·감독":
      return "PD_감독";
    case "콘텐츠기획·에디터":
      return "콘텐츠기획_에디터";
    case "방송작가":
      return "방송작가";
    case "촬영감독·카메라":
      return "촬영감독_카메라";
    case "영상편집":
      return "영상편집";
    case "CG·모션그래픽":
      return "CG_모션그래픽";
    case "사운드디자이너":
      return "사운드디자이너";
    case "기자·리포터":
      return "기자_리포터";
    case "아나운서·쇼호스트":
      return "아나운서_쇼호스트";
    case "성우·나래이터":
      return "성우_나래이터";
    case "크리에이터·인플루언서":
      return "크리에이터_인플루언서";
    case "모델·연기자":
      return "모델_연기자";
    case "사진작가":
      return "사진작가";
    case "방송기술·중계":
      return "방송기술_중계";
    case "송출·편성":
      return "송출_편성";
    case "아티스트매니지먼트":
      return "아티스트매니지먼트";
    case "배급·제작사":
      return "배급_제작사";
    case "음원·음반":
      return "음원_음반";
    case "웹툰·웹소설":
      return "웹툰_웹소설";
    case "출판":
      return "출판";
    case "통·번역":
      return "통_번역";
    case "기타 미디어·엔터":
      return "기타미디어_엔터";

    // 고객상담/TM
    case "인바운드":
      return "인바운드";
    case "아웃바운드":
      return "아웃바운드";
    case "CS":
      return "CS";
    case "CX매니저":
      return "CX매니저";
    case "기타고객상담":
      return "기타고객상담";

    // 서비스
    case "설치·수리기사":
      return "설치_수리기사";
    case "주차·주유":
      return "주차_주유";
    case "가사도우미":
      return "가사도우미";
    case "애견미용·훈련":
      return "애견미용_훈련";
    case "경호·경비":
      return "경호_경비";
    case "호텔서비스":
      return "호텔서비스";
    case "관광서비스":
      return "관광서비스";
    case "항공서비스":
      return "항공서비스";
    case "매장운영·관리":
      return "매장운영_관리";
    case "안내·리셉션":
      return "안내_리셉션";
    case "헤어디자이너":
      return "헤어디자이너";
    case "메이크업·네일":
      return "메이크업_네일";
    case "피부관리":
      return "피부관리";
    case "마사지·체형관리":
      return "마사지_체형관리";
    case "웨딩플래너":
      return "웨딩플래너";
    case "환경미화원":
      return "환경미화원";
    case "기타서비스":
      return "기타서비스";

    // 식음료
    case "식품가공·개발":
      return "식품가공_개발";
    case "주방조리":
      return "주방조리";
    case "제과·제빵":
      return "제과_제빵";
    case "음료·주류":
      return "음료_주류";
    case "매장운영/관리":
      return "매장운영_관리_식음";
    case "서비스·홀스태프":
      return "서비스_홀스태프";
    case "식음컨설팅·지원":
      return "식음컨설팅_지원";
    case "기타식음료":
      return "기타식음료";
  }
}

// 세부분야 역방향 변환 (변수명 → 화면 표시명)
export function getDetailJobCategoryDisplay(enumValue: string) {
  switch(enumValue) {
    // IT·개발
    case "서버_백엔드":
      return "서버·백엔드";
    case "프론트엔드":
      return "프론트엔드";
    case "웹풀스택":
      return "웹풀스택";
    case "안드로이드":
      return "안드로이드";
    case "iOS":
      return "iOS";
    case "크로스_플랫폼":
      return "크로스 플랫폼";
    case "DBA":
      return "DBA";
    case "DevOps_SRE":
      return "DevOps·SRE";
    case "시스템_네트워크":
      return "시스템·네트워크";
    case "시스템소프트웨어":
      return "시스템소프트웨어";
    case "소프트웨어_엔지니어":
      return "소프트웨어 엔지니어";
    case "정보보호_보안":
      return "정보보호·보안";
    case "임베디드소프트웨어":
      return "임베디드 소프트웨어";
    case "로봇SW":
      return "로봇SW";
    case "QA_테스트":
      return "QA·테스트";
    case "사물인터넷_IoT":
      return "사물인터넷(IoT)";
    case "응용_프로그램":
      return "응용 프로그램";
    case "블록체인":
      return "블록체인";
    case "개발PM":
      return "개발PM";
    case "웹퍼블리싱":
      return "웹 퍼블리싱";
    case "VR_AR_3D":
      return "VR·AR·3D";
    case "ERP_SAP":
      return "ERP·SAP";
    case "그래픽스":
      return "그래픽스";
    case "하드웨어엔지니어":
      return "하드웨어엔지니어";
    case "기타IT_개발":
      return "기타IT·개발";
    case "기술지원":
      return "기술지원";

    // AI·데이터
    case "데이터_분석가":
      return "데이터 분석가";
    case "데이터_사이언티스트":
      return "데이터 사이언티스트";
    case "데이터_엔지니어":
      return "데이터 엔지니어";
    case "머신러닝_엔지니어":
      return "머신러닝 엔지니어";
    case "멀티모달엔지니어":
      return "멀티모달엔지니어";
    case "생성형AI":
      return "생성형AI";
    case "영상_음성AI":
      return "영상·음성AI";
    case "자율주행":
      return "자율주행";
    case "컴퓨터비전":
      return "컴퓨터 비전";
    case "AI_비즈니스":
      return "AI 비즈니스";
    case "AI_서비스_기획":
      return "AI 서비스 기획";
    case "AI리서치":
      return "AI리서치";
    case "NLP":
      return "NLP";
    case "LLM":
      return "LLM";
    case "MLOps":
      return "MLOps";
    case "RAG":
      return "RAG";
    case "기타AI_데이터":
      return "기타AI·데이터";

    // 게임
    case "게임기획_PM":
      return "게임기획·PM";
    case "게임운영":
      return "게임운영";
    case "게임QA":
      return "게임QA";
    case "게임개발_클라이언트":
      return "게임개발(클라이언트)";
    case "게임개발_서버":
      return "게임개발(서버)";
    case "게임개발_모바일":
      return "게임개발(모바일)";
    case "테크니컬아티스트":
      return "테크니컬아티스트";
    case "게임아트":
      return "게임아트";
    case "게임3D모델링":
      return "게임3D모델링";
    case "게임애니메이션":
      return "게임애니메이션";
    case "게임이펙트_FX":
      return "게임이펙트·FX";
    case "게임인터페이스":
      return "게임인터페이스";
    case "게임연출_영상":
      return "게임연출·영상";
    case "게임사운드":
      return "게임사운드";
    case "기타게임":
      return "기타게임";

    // 디자인
    case "UIUX_프로덕트":
      return "UIUX·프로덕트";
    case "웹디자인":
      return "웹디자인";
    case "디자인리서치":
      return "디자인리서치";
    case "그래픽_시각":
      return "그래픽·시각";
    case "일러스트레이터":
      return "일러스트레이터";
    case "브랜딩_BIBX":
      return "브랜딩·BIBX";
    case "공간_실내_VMD":
      return "공간·실내·VMD";
    case "산업_제품":
      return "산업(제품)";
    case "패키지":
      return "패키지";
    case "광고_콘텐츠":
      return "광고·콘텐츠";
    case "영상_모션":
      return "영상·모션";
    case "VFX_3D":
      return "3D·VFX";
    case "출판_편집":
      return "출판·편집";
    case "건축_공공_조경디자인":
      return "건축·공공·조경디자인";
    case "패션_텍스타일":
      return "패션·텍스타일";
    case "기타디자인":
      return "기타디자인";

    // 기획·전략
    case "PM_PO":
      return "PM·PO";
    case "서비스_상품기획":
      return "서비스·상품기획";
    case "사업_전략기획":
      return "사업·전략기획";
    case "컨설팅":
      return "컨설팅";
    case "기술기획":
      return "기술기획";
    case "사업개발_분석":
      return "사업개발·분석";
    case "프로젝트_매니저":
      return "프로젝트 매니저";
    case "운영관리_OM":
      return "운영관리(OM)";
    case "경영지원":
      return "경영지원";
    case "기타기획_전략_경영":
      return "기타기획·전략·경영";

    // 마케팅
    case "마케팅기획_전략":
      return "마케팅기획·전략";
    case "퍼포먼스마케팅":
      return "퍼포먼스 마케팅";
    case "콘텐츠마케팅":
      return "콘텐츠마케팅";
    case "SNS마케팅":
      return "SNS마케팅";
    case "브랜드마케팅":
      return "브랜드 마케팅";
    case "CRM마케팅":
      return "CRM마케팅";
    case "글로벌마케팅":
      return "글로벌 마케팅";
    case "광고기획_AE":
      return "광고기획(AE)";
    case "홍보_PR":
      return "홍보·PR";
    case "전시_행사마케팅":
      return "전시·행사 마케팅";
    case "기타마케팅":
      return "기타마케팅";

    // 상품기획/MD
    case "상품기획":
      return "상품기획";
    case "온라인MD":
      return "온라인MD";
    case "식품MD":
      return "식품MD";
    case "패션MD":
      return "패션MD";
    case "뷰티MD":
      return "뷰티MD";
    case "영업MD":
      return "영업MD";
    case "리테일MD":
      return "리테일MD";
    case "기타상품기획_MD":
      return "기타상품기획·MD";

    // 영업
    case "B2C영업":
      return "B2C영업";
    case "B2B영업":
      return "B2B영업";
    case "영업관리_지원":
      return "영업관리·지원";
    case "일반영업":
      return "일반영업";
    case "기술_IT영업":
      return "기술·IT영업";
    case "금융_보험영업":
      return "금융·보험영업";
    case "해외영업":
      return "해외영업";
    case "제약_의료영업":
      return "제약·의료영업";
    case "기타영업":
      return "기타 영업";
    case "해외_상사영업":
      return "해외·상사영업";
    case "구매":
      return "구매";

    // 무역·물류
    case "수출입관리_사무":
      return "수출입관리·사무";
    case "관세사":
      return "관세사";
    case "무역금융":
      return "무역금융";
    case "포워딩":
      return "포워딩";
    case "구매_조달":
      return "구매·조달";
    case "물류_SCM":
      return "물류·SCM";
    case "입출고_포장":
      return "입출고·포장";
    case "자재_재고관리":
      return "자재·재고관리";
    case "운송":
      return "운송";
    case "유통관리":
      return "유통관리";
    case "설비_시설관리":
      return "설비·시설관리";
    case "기타무역_물류_유통":
      return "기타무역·물류·유통";
    case "배송_배달":
      return "배송·배달";
    case "승객운송":
      return "승객운송";
    case "물류운송":
      return "물류운송";
    case "전문운전":
      return "전문운전";
    case "배차관리":
      return "배차관리";
    case "기타운전_운송":
      return "기타운전·운송";

    // 법률
    case "변호사":
      return "변호사";
    case "변리사":
      return "변리사";
    case "법무":
      return "법무";
    case "컴플라이언스":
      return "컴플라이언스";
    case "내부감사":
      return "내부감사";
    case "ESG_윤리":
      return "ESG·윤리";
    case "특허_IP":
      return "특허·IP";
    case "기타법률":
      return "기타법률";

    // HR/총무
    case "인사기획":
      return "인사기획";
    case "평가_보상":
      return "평가·보상";
    case "HRD_조직문화":
      return "HRD·조직문화";
    case "리크루터_헤드헌터":
      return "리크루터·헤드헌터";
    case "노무관리":
      return "노무관리";
    case "총무_비서":
      return "총무·비서";
    case "기타HR_총무":
      return "기타 HR·총무";

    // 회계/세무/재무
    case "회계":
      return "회계";
    case "재무":
      return "재무";
    case "세무":
      return "세무";
    case "IR_공시":
      return "IR_공시";
    case "경리_회계보조":
      return "경리_회계보조";
    case "기타회계_재무_세무":
      return "기타회계_재무_세무";

    // 포털/채용 플랫폼
    case "직행수집":
      return "직행수집";
    case "원티드":
      return "원티드";
    case "그룹바이":
      return "그룹바이";
    case "랠릿":
      return "랠릿";
    case "로켓펀치":
      return "로켓펀치";
    case "고용24":
      return "고용24";
    case "아이원잡":
      return "아이원잡";
    case "중소벤처기업진흥공단":
      return "중소벤처기업진흥공단";
    case "IBRIC":
      return "IBRIC";
    case "클린아이":
      return "클린아이";
    case "아트모아":
      return "아트모아";
    case "복지넷":
      return "복지넷";
    case "한국상담학회":
      return "한국상담학회";
    case "잡스포이즈":
      return "잡스포이즈";
    case "금융투자협회":
      return "금융투자협회";
    case "한국금융벤처캐피탈협회":
      return "한국금융벤처캐피탈협회";
    case "한국공인회계사회":
      return "한국공인회계사회";
    case "여신금융협회":
      return "여신금융협회";
    case "한국관세사회":
      return "한국관세사회";
    case "한국보험계리사회":
      return "한국보험계리사회";
    case "인재채움뱅크":
      return "인재채움뱅크";
    case "잡알리오":
      return "잡알리오";
    case "나라일터":
      return "나라일터";
    case "농촌일자리플러스":
      return "농촌일자리플러스";
    case "도농인력중개플랫폼":
      return "도농인력중개플랫폼";
    case "국민참여일자리":
      return "국민참여일자리";
    case "외교부인사센터":
      return "외교부인사센터";
    case "대한상공회의소":
      return "대한상공회의소";
    case "병역일터":
      return "병역일터";

    // 금융/증권/운용
    case "운용_트레이딩":
      return "운용·트레이딩";
    case "리스크_준법_심사":
      return "리스크·준법·심사";
    case "VC_PE":
      return "VC·PE";
    case "증권IB":
      return "증권IB";
    case "부동산_인프라금융":
      return "부동산·인프라금융";
    case "PB_WM":
      return "PB·WM";
    case "경영지원_관리":
      return "경영지원·관리";
    case "금융상품개발_영업":
      return "금융상품개발·영업";
    case "기타증권_운용":
      return "기타증권·운용";
    case "은행":
      return "은행";
    case "카드사":
      return "카드사";
    case "캐피탈":
      return "캐피탈";
    case "보험설계":
      return "보험설계";
    case "계리":
      return "계리";
    case "손해사정":
      return "손해사정";
    case "언더라이팅_심사":
      return "언더라이팅·심사";
    case "청구_보상":
      return "청구·보상";
    case "보험상품개발":
      return "보험상품개발";
    case "기타은행_보험":
      return "기타은행·보험";

    // 엔지니어링/R&D
    case "반도체_디스플레이":
      return "반도체·디스플레이";
    case "전기_전자_제어":
      return "전기·전자·제어";
    case "통신기술_네트워크구축":
      return "통신기술·네트워크구축";
    case "기계":
      return "기계";
    case "기계설계_CAD":
      return "기계설계·CAD";
    case "자동차":
      return "자동차";
    case "조선_항공_우주":
      return "조선·항공·우주";
    case "금속_철강":
      return "금속·철강";
    case "화학":
      return "화학";
    case "화장품":
      return "화장품";
    case "바이오_제약":
      return "바이오·제약";
    case "식품":
      return "식품";
    case "에너지":
      return "에너지";
    case "환경":
      return "환경";
    case "기타엔지니어링_RnD":
      return "기타엔지니어링·R&D";
    case "자동화":
      return "자동화";

    // 건설/건축
    case "건축설계_시공":
      return "건축설계·시공";
    case "토목_측량_조경_환경":
      return "토목·측량·조경·환경";
    case "기계_전기_소방_설비":
      return "기계·전기·소방·설비";
    case "설계_감리_시공_공무":
      return "설계·감리·시공·공무";
    case "안전_품질_재료":
      return "안전·품질·재료";
    case "사무_관리_전산":
      return "사무·관리·전산";
    case "건설특수_일용직":
      return "건설특수·일용직";
    case "기타건설_건축":
      return "기타건설·건축";

    // 생산/기능직
    case "생산":
      return "생산";
    case "공무":
      return "공무";
    case "설비":
      return "설비";
    case "환경안전":
      return "환경안전";
    case "물류":
      return "물류";
    case "품질":
      return "품질";
    case "건설_공사_프로젝트":
      return "건설·공사·프로젝트";
    case "설계_CAD_CAM":
      return "설계·CAD·CAM";
    case "시설관리":
      return "시설관리";
    case "기타생산_기능직":
      return "기타생산·기능직";

    // 의료/보건
    case "의사":
      return "의사";
    case "한의사":
      return "한의사";
    case "수의사":
      return "수의사";
    case "약사_약무보조":
      return "약사·약무보조";
    case "간호사":
      return "간호사";
    case "간호조무사":
      return "간호조무사";
    case "치위생사":
      return "치위생사";
    case "응급구조사":
      return "응급구조사";
    case "물리치료_작업치료":
      return "물리치료·작업치료";
    case "영상의학_임상병리_검사":
      return "영상의학·임상병리·검사";
    case "영양사_임상영양사":
      return "영양사·임상영양사";
    case "의료미용_에스테틱":
      return "의료미용·에스테틱";
    case "병원행정_접수_수납":
      return "병원행정·접수·수납";
    case "요양보호사":
      return "요양보호사";
    case "조리원":
      return "조리원";
    case "안경_검안사":
      return "안경·검안사";
    case "기타의료_보건":
      return "기타의료·보건";

    // 공공/복지
    case "행정_사무_운영":
      return "행정·사무·운영";
    case "기술_전산_시설":
      return "기술·전산·시설";
    case "복지_사회서비스":
      return "복지·사회서비스";
    case "교육_연구":
      return "교육·연구";
    case "공공안전":
      return "공공안전";
    case "상담_심리":
      return "상담·심리";
    case "종교":
      return "종교";
    case "아동_청소년복지":
      return "아동·청소년복지";
    case "노인_여성복지":
      return "노인·여성복지";
    case "자원봉사":
      return "자원봉사";
    case "기타공공_복지":
      return "기타공공·복지";

    // 교육
    case "유치원_보육교사":
      return "유치원·보육교사";
    case "기간제_사립교사":
      return "기간제·사립교사";
    case "방과후_사립교사":
      return "방과후·사립교사";
    case "대학교수_강사":
      return "대학교수·강사";
    case "교직원_조교":
      return "교직원·조교";
    case "입시학원강사":
      return "입시학원강사";
    case "국어_외국어강사":
      return "국어·외국어강사";
    case "기술_전문강사":
      return "기술·전문강사";
    case "학습지_방문교사":
      return "학습지·방문교사";
    case "학원상담_운영":
      return "학원상담·운영";
    case "교재개발_교수설계":
      return "교재개발·교수설계";
    case "기타교육":
      return "기타교육";
    case "교육관리":
      return "교육관리";

    // 미디어/엔터
    case "PD_감독":
      return "PD·감독";
    case "콘텐츠기획_에디터":
      return "콘텐츠기획·에디터";
    case "방송작가":
      return "방송작가";
    case "촬영감독_카메라":
      return "촬영감독·카메라";
    case "영상편집":
      return "영상편집";
    case "CG_모션그래픽":
      return "CG·모션그래픽";
    case "사운드디자이너":
      return "사운드디자이너";
    case "기자_리포터":
      return "기자·리포터";
    case "아나운서_쇼호스트":
      return "아나운서·쇼호스트";
    case "성우_나래이터":
      return "성우·나래이터";
    case "크리에이터_인플루언서":
      return "크리에이터·인플루언서";
    case "모델_연기자":
      return "모델·연기자";
    case "사진작가":
      return "사진작가";
    case "방송기술_중계":
      return "방송기술·중계";
    case "송출_편성":
      return "송출·편성";
    case "아티스트매니지먼트":
      return "아티스트매니지먼트";
    case "배급_제작사":
      return "배급·제작사";
    case "음원_음반":
      return "음원·음반";
    case "웹툰_웹소설":
      return "웹툰·웹소설";
    case "출판":
      return "출판";
    case "통_번역":
      return "통·번역";
    case "기타미디어_엔터":
      return "기타 미디어·엔터";

    // 고객상담/TM
    case "인바운드":
      return "인바운드";
    case "아웃바운드":
      return "아웃바운드";
    case "CS":
      return "CS";
    case "CX매니저":
      return "CX매니저";
    case "기타고객상담":
      return "기타고객상담";

    // 서비스
    case "설치_수리기사":
      return "설치·수리기사";
    case "주차_주유":
      return "주차·주유";
    case "가사도우미":
      return "가사도우미";
    case "애견미용_훈련":
      return "애견미용·훈련";
    case "경호_경비":
      return "경호·경비";
    case "호텔서비스":
      return "호텔서비스";
    case "관광서비스":
      return "관광서비스";
    case "항공서비스":
      return "항공서비스";
    case "매장운영_관리":
      return "매장운영·관리";
    case "안내_리셉션":
      return "안내·리셉션";
    case "헤어디자이너":
      return "헤어디자이너";
    case "메이크업_네일":
      return "메이크업·네일";
    case "피부관리":
      return "피부관리";
    case "마사지_체형관리":
      return "마사지·체형관리";
    case "웨딩플래너":
      return "웨딩플래너";
    case "환경미화원":
      return "환경미화원";
    case "기타서비스":
      return "기타서비스";

    // 식음료
    case "식품가공_개발":
      return "식품가공·개발";
    case "주방조리":
      return "주방조리";
    case "제과_제빵":
      return "제과·제빵";
    case "음료_주류":
      return "음료·주류";
    case "매장운영_관리_식음":
      return "매장운영/관리";
    case "서비스_홀스태프":
      return "서비스·홀스태프";
    case "식음컨설팅_지원":
      return "식음컨설팅·지원";
    case "기타식음료":
      return "기타식음료";
  }
}
export function changeRecruitmentTypeKorToEnum (recruitmentType: RecruitmentTypeKor) {
  switch (recruitmentType) {
    case '정규직':
      return 'FULL_TIME'
    case '계약직':
      return 'CONTRACT'
    case '일용직':
          return 'DAY_WORKER'
    case '전환형 인턴':
      return 'CONVERTIBLE_INTERN'
    case '체험형 인턴':
      return 'EXPERIENTIAL_INTERN'
    case '프리랜서':
      return 'FREELANCER'
    case '산업기능요원':
      return 'ALTERNATIVE_MILITARY_SERVICE'
  }
}
export function changeRecruitmentTypeEnumToKor (recruitmentType: RecruitmentTypeEnum)  {
  switch (recruitmentType) {
    case 'FULL_TIME':
      return '정규직'
    case 'CONTRACT':
      return '계약직'
    case 'DAY_WORKER':
      return '일용직'
    case 'CONVERTIBLE_INTERN':
      return '전환형 인턴'
    case 'EXPERIENTIAL_INTERN':
      return '체험형 인턴'
    case 'FREELANCER':
      return '프리랜서'
    case 'ALTERNATIVE_MILITARY_SERVICE':
      return '산업기능요원'
  }
}
